apiVersion: v1
kind: Service

metadata:
  name: ai-assistant-api-metrics
  namespace: life-gamefication-dev
  labels:
    app: ai-assistant-api

spec:
  selector:
    app: ai-assistant-api

  ports:
    - name: metrics
      port: 8889
      targetPort: 8889
